site:
  url: "http://127.0.0.1:8000"
  title: "snow"
  language: "zh"

mode.publish:
  site:
    url: "https://honmaple.me"
  languages.en:
    site.url: "http://honmaple.me/en"

# languages.en:
#   site:
#     url: "http://127.0.0.1:8000/en"
#   output_dir: "output/en"

sections:
  _default:
    path: ""
    templates: "posts.html"
    page.template: "page.html"
  posts:
    path: "posts/index.html"
    paginate_path: ""
    page.path: "articles/{date:%Y}/{date:%m}/{slug}.html"
    page.template: "post.html"
  pages:
    page.path: "pages/{slug}.html"
    page.hidden: true

pages:
  _default:
    path: "articles/{date:%Y}/{date:%m}/{slug}.html"
    templates: "post.html"
  en:
    lang: "en"
  pages:
    path: "pages/{slug}.html"
    template: "page.html"
    hidden: true
  drafts:
    draft: true

taxonomies:
  _defualt:
    template: "{taxonomy}/list.html"
    term.template: "{taxonomy}/single.html"
  tags:
    template: "tags/list.html"
    term.template: "tags/single.html"
  authors:
    template: "tags/list.html"
    term.template: "tags/single.html"

output_dir: "output"
content_dir: "content"

ignored_static:
  - js/encrypt.js

statics:
  robots.txt:
    path: "robots.txt"
