base_url: "http://127.0.0.1:8000"
title: "snow"
language: "zh"

mode.publish:
  base_url: "https://honmaple.me"

pages:
  pages:
    hidden: true
  drafts:
    draft: true

taxonomies:
  tags:

output_dir: "output"
